#!/bin/csh
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
#
# The following shell script assumes your NAMD executable is namd3 and that
# the NAMD inputs are located in the current directory.
#
# Only one processor is used below. To parallelize NAMD, use this scheme:
#     charmrun namd3 +p4 input_file.inp > output_file.out
# where the "4" in "+p4" is replaced with the actual number of processors you
# intend to use.

NAMD_CORES = "$1"
GPU_DEVICE = "$2"

set equi_prefix = step4_equilibration
set prod_prefix = step5_production
set prod_step   = step5

set namd = bin/namd3_IMDv3_gpu_mc

# Running equilibration step
./$namd +p${NAMD_CORES} +devices ${GPU_DEVICE} input/${equi_prefix}.inp > output/${equi_prefix}.out