#!/bin/bash

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

# Arguments
NAMD_CORES="$1"   # Number of CPU cores for NAMD
GPU_DEVICE="$2"   # GPU device to use
n_runs="$3"       # Number of runs

# Variables
equi_prefix="step4_equilibration"
prod_prefix="step5_production_imdv3_fileio"
prod_step="step5_imdv3_fileio"

namd="bin/namd3_IMDv3_gpu_mc"

# Running production for 10 nanoseconds
cntmax=1

for run in $(seq 1 "$n_runs"); do
    # Check if directory exists before creating it
    if [[ ! -d "output/run-${run}" ]]; then
        mkdir -p "output/run-${run}"
    fi

    cnt=1

    while [[ $cnt -le $cntmax ]]; do
        # Create appropriate input file using ${prod_prefix}.inp as a template
        if [[ $cnt -eq 1 ]]; then
            outputname="${prod_step}_${cnt}"
            # Change only the output name
            sed "s/${prod_prefix}/${outputname}/" "input/${prod_prefix}.inp" > "input/${prod_step}_run.inp"
            # Change output/ to output/run-${run}/ in the input file (only first occurrence)
            sed -i "0,/output\//s//output\/run-${run}\//" "input/${prod_step}_run.inp"
        else
            cntprev=$((cnt - 1))
            inputname="${prod_step}_${cntprev}"
            outputname="${prod_step}_${cnt}"
            # Change input and output names from the template file
            sed "s/${equi_prefix}/${inputname}/" "input/${prod_prefix}.inp" | \
                sed "s/${prod_prefix}/${outputname}/" > "input/${prod_step}_run.inp"
            # Change output/ to output/run-${run}/ in the input file
            sed -i "s|output/|output/run-${run}/|g" "input/${prod_step}_run.inp"
        fi

        # Run the simulation for 1 nanosecond with CPU affinity
        taskset -c 0-$((NAMD_CORES - 1)) ./"$namd" +p"$NAMD_CORES" +devices "$GPU_DEVICE" "input/${prod_step}_run.inp" > "output/run-${run}/${outputname}.out" &
        wait

        cnt=$((cnt + 1))
    done
done
