#!/usr/bin/env bash

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

# Get CPU IDs from "thisjob" output; if not available, fall back to SLURM_JOB_CPUS_LIST
cpu_ids=$(thisjob | grep CPU_IDs | sed -E 's/.*CPU_IDs=([^ ]+).*/\1/')
if [[ -z "$cpu_ids" ]]; then
    if [[ -z "$SLURM_JOB_CPUS_LIST" ]]; then
        echo "SLURM_JOB_CPUS_LIST is not set."
        exit 1
    else
        cpu_ids="$SLURM_JOB_CPUS_LIST"
    fi
fi

# Function to expand a CPU list (e.g., "1-2,20-21,42-45") into an array of individual cores
expand_cpu_list() {
    local list="$1"
    local expanded=()
    IFS=',' read -ra ranges <<< "$list"
    for range in "${ranges[@]}"; do
        if [[ "$range" == *"-"* ]]; then
            IFS='-' read -r start end <<< "$range"
            for (( i=start; i<=end; i++ )); do
                expanded+=("$i")
            done
        else
            expanded+=("$range")
        fi
    done
    echo "${expanded[@]}"
}

# Expand the allocated CPU IDs into an array
allocated=($(expand_cpu_list "$cpu_ids"))

# Input parameters (passed as command-line arguments)
NAMD_CORES="$1"   # Number of cores for NAMD
GPU_DEVICE="$2"   # GPU device to use
COMMON_LOG="$3"   # Common log information
EXEC_NAME="${4:-bin/namd_multicore_gpuresident_vanilla}" # Default executable if not provided
INPUT_FILE="${5:-input/step4_equilibration.inp}" # Default input file if not provided

# Get the list for NAMD cores (first NAMD_CORES from the allocated list)
namd_cores_array=("${allocated[@]:0:$NAMD_CORES}")
namd_core_list=$(IFS=, ; echo "${namd_cores_array[*]}")

# Running NAMD on the specified CPU cores and GPU device
echo "Running NAMD on CPU cores: $namd_core_list and GPU device: $GPU_DEVICE"

# Variables
equi_prefix="step4_equilibration"
namd="$EXEC_NAME"

equi_dir="output/vanilla/performance/equil/1-0-$NAMD_CORES/run-1"
# make this directory if it does not exist
mkdir -p "$equi_dir"

md_start_time=$(date "+%Y-%m-%dT%H:%M:%S")

# Create a temporary input file with the correct output directory path
# This ensures DCD, restart files, etc. go to the right location
equilrun_input_file="input/step4_equilibration_equilrun.inp"
sed "s|^outputName.*|outputName          ../${equi_dir}/${equi_prefix};|" "$INPUT_FILE" > "$equilrun_input_file"

# Determine how to call the binary (handle absolute vs relative paths)
if [[ "$namd" == /* ]]; then
    namd_cmd="$namd"  # Absolute path
else
    namd_cmd="./$namd"  # Relative path
fi

# Run the equilibration step with taskset using the determined CPU core list
taskset -c "$namd_core_list" "$namd_cmd" +p"${NAMD_CORES}" +devices "${GPU_DEVICE}" "$equilrun_input_file" > "${equi_dir}/${equi_prefix}.out" 2>&1 &
wait

# Clean up temporary input file
rm -f "$equilrun_input_file"

md_end_time=$(date "+%Y-%m-%dT%H:%M:%S")

LOG_FILE="job_info_${SLURM_JOB_ID}.log"
echo "$COMMON_LOG" > "${equi_dir}/$LOG_FILE"

# 2) Append equil-specific lines:
{
    echo "Type of Simulation: vanilla"
    echo "Type of Run: equil"
    echo "MD Started: $md_start_time"
    echo "MD Ended: $md_end_time"
} >> "${equi_dir}/$LOG_FILE"
