#!/bin/csh
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
#
# This folder contains GROMACS formatted force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx mdrun -ntomp 1

#set init = ../GROMACS_INPUT/step3_input
#set mini_prefix = ../GROMACS_INPUT/step4.0_minimization
#set equi_prefix = ../GROMACS_INPUT/step4.1_equilibration
#set prod_prefix = ../GROMACS_INPUT/step5_production
#set prod_step   = ../GROMACS_INPUT/step5

# Minimization
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.
#gmx grompp -f ${mini_prefix}.mdp -o ${mini_prefix}.tpr -c ${init}.gro -r ${init}.gro -p ../GROMACS_INPUT/topol.top -n ../GROMACS_INPUT/index.ndx -maxwarn 1
#gmx mdrun -v -deffnm step4.0_minimization 


# Equilibration
#gmx grompp -f ${equi_prefix}.mdp -o ${equi_prefix}.tpr -c ${mini_prefix}.gro -r ${init}.gro -p ../GROMACS_INPUT/topol.top -n ../GROMACS_INPUT/topol.top.ndx
#gmx mdrun -v -deffnm step4.1_equilibration

# Minimization
gmx grompp -f ../GROMACS_INPUT/step4.0_minimization.mdp -o step4.0_minimization.tpr -c ../GROMACS_INPUT/step3_input.gro -r ../GROMACS_INPUT/step3_input.gro -p ../GROMACS_INPUT/topol.top -n ../GROMACS_INPUT/index.ndx -maxwarn 1
gmx mdrun -v -deffnm step4.0_minimization >& min.out

# Equilibration
gmx grompp -f ../GROMACS_INPUT/step4.1_equilibration.mdp -o step4.1_equilibration.tpr -c step4.0_minimization.gro -r ../GROMACS_INPUT/step3_input.gro -p ../GROMACS_INPUT/topol.top -n ../GROMACS_INPUT/index.ndx
gmx mdrun -v -deffnm step4.1_equilibration >& equi.out
